name: github_webhooks
description: Helper functions for Dart microservices responding to GitHub webhooks.
version: 0.0.0-a1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
